## ルールベースでやったらいけんじゃね？

In [1]:
import pandas as pd
train = pd.read_csv("../data/train.csv")
test = pd.read_csv("../data/test.csv")
sub = pd.read_csv("../exp_13/output/submit.csv")

In [2]:
train.head(1)

ncode      general_firstup        title  \
0  N7588B  2007-04-01 16:40:57  暗い窓辺と皇帝の北の宮   

                                               story            keyword  \
0  ※新しく手直ししました。\n\nhttp://ncode.syosetu.com/n2539...  ファンタジー SF 天使 小人 猫   

   userid writer  biggenre  genre  novel_type  end  isstop  isr15  isbl  isgl  \
0    9904   梅田浩志         4    402           1    0       0      0     0     0   

   iszankoku  istensei  istenni  pc_or_k  fav_novel_cnt_bin  
0          0         0        0        0                  1

In [3]:
sub.head()

ncode   proba_0   proba_1   proba_2   proba_3   proba_4
0  N0001HE  0.885728  0.110121  0.003019  0.000802  0.000330
1  N0002HE  0.183997  0.795386  0.018803  0.001382  0.000432
2  N0004HF  0.602183  0.368384  0.023715  0.004504  0.001214
3  N0005HE  0.004398  0.016972  0.374448  0.583504  0.020678
4  N0006HF  0.052164  0.504064  0.394847  0.040554  0.008370

In [4]:
from collections import Counter
import numpy as np

In [5]:
test = test.sort_values("ncode").reset_index(drop=True)

In [6]:
cnt = 0
ncode_dict = {}
for i, row in test.iterrows():
    if row["writer"] in list(train["writer"]):
        l = [0]*5
        d = {0:0, 1:0, 2:0, 3:0, 4:0} 
        tmp_list = train.query("writer == @row['writer']")["fav_novel_cnt_bin"].to_list()
        for j in tmp_list:
            d[j] += 1
        ncode_dict[row["ncode"]] = list(d.values()) / np.sum(list(d.values()))
        cnt+=1
    else:
        ncode_dict[row["ncode"]] = np.nan

print(cnt)

5184


In [7]:
cnt = 0
for i in ncode_dict.keys():
    if type(ncode_dict[i]) == float:
        cnt += 1 
        continue
    else:
        sub.loc[cnt, 1:] = ncode_dict[i]
        cnt += 1

[0.84210526 0.15789474 0.         0.         0.        ]
[0.8857276480429845 0.1101213417647331 0.0030189853055558
 0.0008016093576891 0.0003304155290373]
[0.07407407 0.77777778 0.11111111 0.03703704 0.        ]
[0.1839974693413224 0.7953855950634001 0.0188033881644102
 0.0013815397398207 0.0004320076910464]
[1. 0. 0. 0. 0.]
[0.0043980005879274 0.0169721568408316 0.3744478823340984
 0.5835036195946395 0.020678340642503]
[0.    0.875 0.125 0.    0.   ]
[0.0521642530082633 0.504063733648253 0.3948473690078801
 0.0405541978099599 0.0083704465256435]
[0.25 0.75 0.   0.   0.  ]
[0.2766902128032281 0.6535642505541063 0.0615008245258357
 0.0065299217355232 0.0017147903813065]
[0. 1. 0. 0. 0.]
[0.8578963961603268 0.1338587834520484 0.0066537109577925
 0.001215359688984 0.000375749740848]
[0.85333333 0.10666667 0.04       0.         0.        ]
[0.8996658449868459 0.0962634672994467 0.0029514088683296
 0.0007936259318542 0.0003256529135234]
[0.75757576 0.24242424 0.         0.         0.       

/usr/local/lib/python3.8/site-packages/pandas/core/indexing.py:719: FutureWarning: Slicing a positional slice with .loc is not supported, and will raise TypeError in a future version.  Use .loc with labels or .iloc with positions instead.
  indexer = self._get_setitem_indexer(key)


[0.25 0.75 0.   0.   0.  ]
[0.4356302200716833 0.548410805736991 0.0139140898649105
 0.0015945735769953 0.0004503107494198]
[0.86666667 0.13333333 0.         0.         0.        ]
[0.6980817133680441 0.2741785390840922 0.0205838000340375
 0.0049138695712093 0.0022420779426167]
[0.9 0.1 0.  0.  0. ]
[0.9233317433030654 0.0739049755709382 0.0020002516863961
 0.0005480587907334 0.0002149706488666]
[0.         0.55555556 0.33333333 0.11111111 0.        ]
[0.0458717500386647 0.5258913085865542 0.3719931593742512
 0.0433993100472495 0.0128444719532804]
[1. 0. 0. 0. 0.]
[0.8743394871852525 0.1181157738551881 0.0052125825424046
 0.0017972767265972 0.0005348796905574]
[0.86666667 0.13333333 0.         0.         0.        ]
[0.6972785273969003 0.2785030194608339 0.017515916216084
 0.0044995348707002 0.0022030020554817]
[0. 0. 1. 0. 0.]
[0.0454100889694146 0.3301176767872297 0.4945442412139957
 0.1058092374032534 0.0241187556261062]
[0.         0.         0.16666667 0.83333333 0.        ]
[0.01

In [10]:
sub.to_csv("../output/submit_rulebase.csv", index=False)